kind: Service
apiVersion: v1
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
    - name: ftps-port
      port: 21
      targetPort: 21
      nodePort: 21
    - name: ftps00
      port: 30000
      nodePort: 30000
      targetPort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
          - containerPort: 21
          - containerPort: 30000
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 3
          periodSeconds: 3